name: Add Labels to new issues

on:
  issues:
    types: [opened]

jobs:
  # https://github.com/actions/labeler in order to automatically add labels according to the template used i.e: bug, enhancement
  label_issue_with_triage:
      runs-on: ubuntu-latest
      permissions:
        issues: write
      steps:
        - run: gh issue edit "$NUMBER" --add-label "$LABELS"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_REPO: ${{ github.repository }}
            NUMBER: ${{ github.event.issue.number }}
            LABELS: status:needs triage
  label_with_software:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup labeling script
          run: cd .github/labeler && npm install

        - name: Run labeling script
          run: node .github/labeler/index.js
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}